services:
  db:
    image: mysql:8
    container_name: freya-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: usuarios_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: freya-backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
    working_dir: /app
    command: ["./wait-for-it.sh", "db", "3306", "--", "npm", "start"]

volumes:
  db_data:
